---
dist: xenial
install:
  - "pip install pytest pylint pycodestyle pydocstyle Pillow"
language: python
python:
  - "3.7"
script:
  - pytest
  - pylint image_manipulation.py
  - pycodestyle image_manipulation.py
  - pydocstyle image_manipulation.py
notifications:
  email:
    recipients:
      - user@example.com
    on_success: always
    on_failure: always
